### ISSUE TITLE
Long Texts

### ISSUE THREAD

**Issue by Isabel-S** [systers/FirstAide-iOS#22]
This is a bug I found for the GCI task: Find a bug! [FirstAide - iOS] 
When there are long pieces of text where you need to scroll down, some of them start in the middle rather than starting from the first word. This happened in many scenes:

- RADAR
- Tactics of Sexual Predators
- Bystander Intervention
- Safety Plan Basics
- Safety Plan
- Benefits of Seeking Staff Support
- Available Services After Sexual Assault

This only happens to some cards. Below is a link to a google drive video to show the issue:
[https://drive.google.com/file/d/0B5XB9ILn-H2MejBEYXVpWnFfY1U/view?usp=sharing](url)

**Comment by YashBit** [comment]
@chamika  Can I solve this bug until then ?

**Comment by chamika** [comment]
Yes, Go ahead

**Comment by chamika** [comment]
Bug is fixed. Hence closing

**Comment by jacqueline8711** [comment]
There are still screens where this bug is not fixed, i.e. scroll views start at the bottom (tested on iPhone 5):

- RADAR, Step 3
- Safety Plan (Physical Safety , Workplace, Transportation + all pop-ups)

Can I fix this?

**Comment by chamika** [comment]
Yes. go ahead.
